name: coords
main: unerds\coords\coords
version: 1.0.0
api: 5.0.0
author: unerds
permissions:
 xyz.coords
commands:
 coords:
  description: Returns Player Coordinates
  usage: "/coords"
  permission: xyz.coords
